site_name: Tech Wiki
nav:
  - Home: index.md
  - Infrastructure:
      - Emby Setup: movie-pipeline/emby/setup.md
      - Emby Remote Access: movie-pipeline/emby/tailscale.md
      - Library Management: movie-pipeline/emby/library-management.md
  - Media Workflow:
      - Ripping (MakeMKV): movie-pipeline/makemkv/ripping.md
      - Compression (HandBrake): movie-pipeline/handbrake/compression.md
  - Homelab Maintenance:
      - Introduction: homelab-maintenance/index.md
theme: 
  name: mkdocs
  color_mode: dark