site_name: Tech Wiki
site_url: https://wiki.hoss-movies.com/
nav:
  - Home: index.md
  - Emby Server:
      - Emby Setup: movie-pipeline/emby/setup.md
      - Ripping (MakeMKV): movie-pipeline/makemkv/ripping.md
      - Compression (HandBrake): movie-pipeline/handbrake/compression.md
      - Emby Remote Access: movie-pipeline/emby/tailscale.md
      - Library Management: movie-pipeline/emby/library-management.md
  - Homelab Maintenance:
      - Introduction: homelab-maintenance/index.md
      - Overview: homelab-maintenance/overview.md
      - Workflows: homelab-maintenance/workflow.md
      - Troubleshooting: homelab-maintenance/troubleshooting.md
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
